theme: jekyll-theme-cayman
google_analytics: UA-189500722-1
title: Speech Morphing
description: This is a summary of speech morphing by Takanori Horibe.
baseurl: "/speech-morphing"

source: .
layouts_dir: _layouts
includes_dir: _includes
show_excerpts: true